### PR TITLE
Add main component

### PR DESCRIPTION
**Pull request by kriskowal**
The main component becomes the new root component, which initially just instantiates the hexant component. It should eventually orchestrate and bind the application controls, leaving the hexant component to be a pure view.

### CODE REVIEW

**Comment by kriskowal** [comment]
Rebased.

**Comment by jcorbin** [comment]
Needs more rebase

**Comment by kriskowal** [comment]
Rererebased.

**Comment by jcorbin** [comment]
Not quite sure what the point of this is yet, but I hope to be smart enough to sort it out some day ;-).  Also since I haven't had the problem of "too much indirection" in this project, then it must be a Good Thing™.

**Pull request merged**
